version: '3'
services:
  server1:
    build: ./server
    environment:
      - SERVER_ID=1
    ports:
      - "5002:5000"

  server2:
    build: ./server
    environment:
      - SERVER_ID=2
    ports:
      - "5003:5000"

  server3:
    build: ./server
    environment:
      - SERVER_ID=3
    ports:
      - "5004:5000"

  balancer:
    build: ./load_balancer
    ports:
      - "5001:5001"